INC_PATH = -I/usr/local/include/player-3.0
LIB_PATH = -L/usr/local/lib64 -lplayerc -lm -lz -lplayerinterface -lplayerwkb -lplayercommon
move: move2.c
	gcc -o move2 $(INC_PATH) move2.c $(LIB_PATH)
clean:
	rm -rf move2
